name: 'my Action'
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: run__
        run: g++ simple_allocator.cpp -std=c++17
      